inputs:
    fastq_dir: /home/lmitch/projects/rrg-zovoilis/lmitch/reditools-snake-pipe/fq-link
    reference: /home/lmitch/projects/rrg-zovoilis/lmitch/reditools-snake-pipe/genome/Mus_musculus.GRCm39.cdna.all.fa
