cluster: 
  mkdir -p logs/{rule} && 
  sbatch
    --partition={resources.partition}
    --qos={resources.qos}
    --cpus-per-task={threads}
    --mem={resources.mem_gb}G
    --time={resources.time}
    --job-name={rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.slurmlog
    --account={resources.account}
default-resources:
  - account=rrg-zovoilis
  - partition=default
  - qos=normal
  - mem_gb=4
  - time="01:00:00"
local-cores: 48
restart-times: 0
max-jobs-per-second: 10
max-status-checks-per-second: 1
latency-wait: 60
jobs: 500
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: False
